export default {
  alert: 'Alert',
  badge: 'Badge',
  box: 'Box',
  button: 'Button',
  checkbox: 'Checkbox',
  collapse: 'Collapse',
  dialog: 'Dialog',
  divider: 'Divider',
  grid: 'Grid',
  input: 'Input',
  label: 'Label',
  link: 'Link',
  progress: 'Progress',
  radio: 'Radio',
  select: 'Select',
  switch: 'Switch',
  table: 'Table',
  tabs: 'Tabs',
  textarea: 'Textarea',
  tooltip: 'Tooltip',
}
