# Workflow
name: Storybook Publish

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          registry-url: https://npm.pkg.github.com/
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm
      - name: Install Node Dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Prepare to Deploy GH-Pages
        run: npm run build-storybook
      - name: Deploy to gh-pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: apps/storybook/storybook-static
          checkout: false
